spring:
  datasource:
    #url: jdbc:mysql://192.168.9.194:30036/URLADMIN?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://125.179.222.102:3306/URLADMIN?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000 # 연결 시도 제한 시간 (30초)
      maximumPoolSize: 100

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  thymeleaf:
    encoding: UTF-8

server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true